; highlights.scm

"header" @keyword
"struct" @keyword
"extern" @keyword
"parser" @keyword
"state" @keyword
"if" @keyword
"else" @keyword
"transition" @keyword
"apply" @keyword
"control" @keyword
"action" @keyword
"table" @keyword
"key" @keyword
"range" @keyword
"lpm" @keyword
"exact" @keyword
"ternary" @keyword
"actions" @keyword
"default_action" @keyword
"return" @keyword
"NoAction" @keyword
(direction) @keyword
"bool" @type
(bit_type) @type
(number) @number
(type_identifier) @type
(method_identifier) @function
(comment) @comment
(preproc) @keyword.directive
