; highlights.scm

"header" @keyword
"struct" @keyword
"typedef" @keyword
"extern" @keyword
"parser" @keyword
"state" @keyword
"if" @keyword
"else" @keyword
"transition" @keyword
"select" @keyword
"apply" @keyword
"control" @keyword
"package" @keyword
"action" @keyword
"table" @keyword
"key" @keyword
"size" @keyword
"range" @keyword
"lpm" @keyword
"exact" @keyword
"ternary" @keyword
"optional" @keyword
"actions" @keyword
"default" @keyword
"default_action" @keyword
"return" @keyword
"NoAction" @keyword
"const" @keyword
"meters" @keyword
"counters" @keyword
"_" @keyword
"true" @constant
"false" @constant
(direction) @keyword
(number) @number
(bit_type) @type
(varbit_type) @type
(tuple_type) @type
"bool" @type
"error" @type
"int" @type
"bit" @type
"tuple" @type
"varbit" @type
"packet_in" @type
"packet_out" @type
(type_identifier) @type
(method_identifier) @function
(comment) @comment
(preproc) @keyword.directive
(annotation) @attribute
